// Code generated by "uaxplc -module=vendor -input=~/dev/php/device-detector/regexes/vendorfragments.yml". DO NOT EDIT.

package uaxpl

import (
	"regexp"
)

var (
	__vr_idx = []vendorTuple{
		vendorTuple{brand64: 0x00000004, range64: 0x00000001},
		vendorTuple{brand64: 0x400000008, range64: 0x100000005},
		vendorTuple{brand64: 0x80000000e, range64: 0x500000009},
		vendorTuple{brand64: 0xe00000012, range64: 0x90000000c},
		vendorTuple{brand64: 0x1200000019, range64: 0xc0000000e},
		vendorTuple{brand64: 0x1900000020, range64: 0xe0000000f},
		vendorTuple{brand64: 0x2000000022, range64: 0xf00000012},
		vendorTuple{brand64: 0x2200000029, range64: 0x1200000013},
		vendorTuple{brand64: 0x290000002f, range64: 0x1300000018},
		vendorTuple{brand64: 0x2f00000032, range64: 0x180000001a},
		vendorTuple{brand64: 0x3200000038, range64: 0x1a0000001b},
		vendorTuple{brand64: 0x3800000041, range64: 0x1b0000001d},
		vendorTuple{brand64: 0x4100000048, range64: 0x1d0000001f},
		vendorTuple{brand64: 0x480000004c, range64: 0x1f00000022},
		vendorTuple{brand64: 0x4c00000053, range64: 0x2200000027},
	}
	__vr_re = []*regexp.Regexp{
		regexp.MustCompile(`MAAR(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MAAU[^a-z0-9]+`),
		regexp.MustCompile(`NP0[26789][^a-z0-9]+`),
		regexp.MustCompile(`ASJB[^a-z0-9]+`),
		regexp.MustCompile(`ASU2(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`CPDTDF[^a-z0-9]+`),
		regexp.MustCompile(`CPNTDF(JS?)[^a-z0-9]+`),
		regexp.MustCompile(`CMNTDF(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`CMDTDF(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MDDR(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MDDC(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MDDS(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MAFS(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`FSJB[^a-z0-9]+`),
		regexp.MustCompile(`MAGW(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`HPCMHP[^a-z0-9]+`),
		regexp.MustCompile(`HPNTDF(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`HPDTDF(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MANM(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MALC(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MALE(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MALN(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`LCJB[^a-z0-9]+`),
		regexp.MustCompile(`LEN2[^a-z0-9]+`),
		regexp.MustCompile(`MAMI(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MAM3[^a-z0-9]+`),
		regexp.MustCompile(`MAMD[^a-z0-9]+`),
		regexp.MustCompile(`Ordissimo[^a-z0-9]+`),
		regexp.MustCompile(`webissimo3[^a-z0-9]+`),
		regexp.MustCompile(`MASM(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`SMJB[^a-z0-9]+`),
		regexp.MustCompile(`MASE(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MASP(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MASA(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MATM(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MATB(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`MATP(JS)?[^a-z0-9]+`),
		regexp.MustCompile(`TNJB[^a-z0-9]+`),
		regexp.MustCompile(`TAJB[^a-z0-9]+`),
	}
	__vr_buf = []byte{
		0x41, 0x63, 0x65, 0x72, 0x41, 0x73, 0x75, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x71, 0x44, 0x65,
		0x6c, 0x6c, 0x46, 0x75, 0x6a, 0x69, 0x74, 0x73, 0x75, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
		0x48, 0x50, 0x48, 0x79, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x4c, 0x65, 0x6e, 0x6f, 0x76, 0x6f, 0x4d,
		0x53, 0x49, 0x4d, 0x65, 0x64, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x64, 0x69, 0x73, 0x73, 0x69, 0x6d,
		0x6f, 0x53, 0x61, 0x6d, 0x73, 0x75, 0x6e, 0x67, 0x53, 0x6f, 0x6e, 0x79, 0x54, 0x6f, 0x73, 0x68,
		0x69, 0x62, 0x61,
	}
)
